/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-dark': 'var(--color-primary-dark)',
        'primary-dark-hover': 'var(--color-primary-dark-hover)',
        secondary: 'var(--color-secondary)',
        'secondary-hover': 'var(--color-secondary-hover)',
        tertiary: 'var(--color-tertiary)',
        'tertiary-hover': 'var(--color-tertiary-hover)',
        'text-primary': 'var(--color-text-primary)',
        'text-primary-hover': 'var(--color-text-primary-hover)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-secondary-hover': 'var(--color-text-secondary-hover)',
        'text-tertiary': 'var(--color-text-tertiary)',
        'text-tertiary-hover': 'var(--color-text-tertiary-hover)',
        'border-primary': 'var(--color-border-primary)',
        'bg-primary': 'var(--color-bg-primary)',
        'bg-secondary': 'var(--color-bg-secondary)',
        'bg-tertiary': 'var(--color-bg-tertiary)',
        'bg-success': 'var(--color-bg-success)',
        'text-success': 'var(--color-text-success)',
        'bg-error': 'var(--color-bg-error)',
        'text-error': 'var(--color-text-error)',
        'bg-warning': 'var(--color-bg-warning)',
        'text-warning': 'var(--color-text-warning)',
        'bg-info': 'var(--color-bg-info)',
        'text-info': 'var(--color-text-info)',
      },
    },
  },
  plugins: [],
}
